"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SunglassesFace = exports.SmirkingFace = exports.KissingFace = exports.ExpressionlessFace = exports.WorriedFace = exports.CoolFace = exports.SickFace = exports.ThinkingFace = exports.SleepingFace = exports.WinkingFace = exports.SurprisedFace = exports.AngryFace = exports.LaughingFace = exports.SmilingFace = exports.NeutralFace = exports.SadFace = exports.HappyFace = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var HappyFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 16c1.5 1 3.5 1 5 0", strokeLinecap: "round" })] }));
};
exports.HappyFace = HappyFace;
var SadFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 16c2 2 4 2 8 0", strokeLinecap: "round" })] }));
};
exports.SadFace = SadFace;
var NeutralFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("line", { x1: "8", y1: "16", x2: "16", y2: "16", strokeLinecap: "round" })] }));
};
exports.NeutralFace = NeutralFace;
var SmilingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 14c1.5 1 3.5 1 5 0", strokeLinecap: "round" })] }));
};
exports.SmilingFace = SmilingFace;
var LaughingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "9", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "9", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 15c2 3 6 3 8 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M9 12h6", strokeLinecap: "round" })] }));
};
exports.LaughingFace = LaughingFace;
var AngryFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("path", { d: "M8 9l-2-1", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M16 9l2-1", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 17c2-1 4-1 6 0", strokeLinecap: "round" })] }));
};
exports.AngryFace = AngryFace;
var SurprisedFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "15", r: "2", fill: filled ? 'white' : 'none' }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "2", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "2", fill: filled ? 'white' : color })] }));
};
exports.SurprisedFace = SurprisedFace;
var WinkingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 10c0.5 0 1-0.5 1-1", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M8 14c1.5 1 3.5 1 5 0", strokeLinecap: "round" })] }));
};
exports.WinkingFace = WinkingFace;
var SleepingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("path", { d: "M8 10h0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M16 10h0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M8 16c2 1 4 1 6 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M6 6l12 6", strokeLinecap: "round" })] }));
};
exports.SleepingFace = SleepingFace;
var ThinkingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "9", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "15", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 15h8", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("circle", { cx: "18", cy: "17", r: "0.5", fill: "none" })] }));
};
exports.ThinkingFace = ThinkingFace;
var SickFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 16c2 1 4 1 6 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M10 7l-2 2", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M14 7l2 2", strokeLinecap: "round" })] }));
};
exports.SickFace = SickFace;
var CoolFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "9", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "15", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 14c2 1 4 1 6 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("circle", { cx: "18", cy: "7", r: "1", fill: "none" })] }));
};
exports.CoolFace = CoolFace;
var WorriedFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "11", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "11", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 16c2.5 1.5 5.5 1.5 8 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M12 8v2", strokeLinecap: "round" })] }));
};
exports.WorriedFace = WorriedFace;
var ExpressionlessFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("line", { x1: "8", y1: "10", x2: "10", y2: "10", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("line", { x1: "14", y1: "10", x2: "16", y2: "10", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("line", { x1: "8", y1: "16", x2: "16", y2: "16", strokeLinecap: "round" })] }));
};
exports.ExpressionlessFace = ExpressionlessFace;
var KissingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("circle", { cx: "16", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M8 14c1 1 3 1 4 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "16", r: "1", fill: filled ? 'white' : color })] }));
};
exports.KissingFace = KissingFace;
var SmirkingFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("circle", { cx: "8", cy: "10", r: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M16 10c0.5 0 1-0.5 1-1", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M8 15c1.5 1 3.5 1 5 0", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M14 8l2 2", strokeLinecap: "round" })] }));
};
exports.SmirkingFace = SmirkingFace;
var SunglassesFace = function (_a) {
    var _b = _a.size, size = _b === void 0 ? 24 : _b, _c = _a.color, color = _c === void 0 ? 'currentColor' : _c, _d = _a.className, className = _d === void 0 ? '' : _d, onClick = _a.onClick, backgroundColor = _a.backgroundColor, _e = _a.strokeWidth, strokeWidth = _e === void 0 ? 2 : _e, _f = _a.filled, filled = _f === void 0 ? false : _f;
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 24 24", fill: filled ? color : 'none', stroke: color, strokeWidth: strokeWidth, className: className, onClick: onClick, children: [(0, jsx_runtime_1.jsx)("circle", { cx: "12", cy: "12", r: "10", fill: backgroundColor }), (0, jsx_runtime_1.jsx)("rect", { x: "7", y: "9", width: "3", height: "2", rx: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("rect", { x: "14", y: "9", width: "3", height: "2", rx: "1", fill: filled ? 'white' : color }), (0, jsx_runtime_1.jsx)("path", { d: "M7 11h10", strokeLinecap: "round" }), (0, jsx_runtime_1.jsx)("path", { d: "M8 14c1.5 1 3.5 1 5 0", strokeLinecap: "round" })] }));
};
exports.SunglassesFace = SunglassesFace;
